name = "forsynth"
version = "0.1.0"
license = ""
author = "Vincent Magnin"
maintainer = "Vincent Magnin"
copyright = "2021 Vincent Magnin"


[library]
source-dir="src"

[[test]]
name="runTests"
source-dir="test"
main="main.f90"

[[executable]]
name="forsynth"
source-dir="app"
main="main.f90"

